id: P11B251DB
initial_creation_type: input
source_metadata:
  title: Shechen Kongtrul Series
  language: en
  description: 'Texts by and about Pema Drimé Lekpé Lodrö (zhe chen kong sprul padma
    dri med legs pa''i blo gros, 1901-c.1960), the immediate reincarnation of Jamgön
    Kongtrul Lodrö Thaye at Shechen Monastery:'
  volume:
    0041c09e225f4c4fb138a719c779f081:
      title: Prayer to Shechen Kongtrul as Vajrasattva
      parent: Prayers
created_at: '2022-03-01T01:35:04.352000'
last_modified_at: '2022-03-01T01:35:04.352006'
